import { Achievement } from "../types";

export const badges: Achievement[] = [
  {
    id: "1",
    name: "First Steps",
    description: "Complete your first contest",
    type: "first",
    rarity: "common",
    earned: false,
    earnedDate: "2024-01-10",
    progress: "",
  },
  {
    id: "2",
    name: "Speed Demon",
    description: "Answer 10 questions in under 30 seconds",
    type: "speed",
    rarity: "rare",
    earned: false,
    earnedDate: "",
    progress: "",
  },
  {
    id: "3",
    name: "Perfectionist",
    description: "Score 100% in any contest",
    type: "perfection",
    rarity: "epic",
    earned: false,
    earnedDate: "",
    progress: "",
  },
  {
    id: "4",
    name: "Streak Master",
    description: "Maintain a 7-day winning streak",
    type: "streak",
    rarity: "rare",
    earned: false,
    earnedDate: "2024-01-20",
    progress: "",
  },
  {
    id: "5",
    name: "Math Wizard",
    description: "Score 90%+ in 5 math contests",
    type: "subject",
    rarity: "epic",
    earned: false,
    earnedDate: "",
    progress: "",
  },
  {
    id: "6",
    name: "Champion",
    description: "Reach top 10 in global leaderboard",
    type: "rank",
    rarity: "legendary",
    earned: false,
    earnedDate: "",
    progress: "",
  },
];
